# 配置项目访问路径
server:
  port: 8080

spring:
  datasource:
    name: mydata
    url: jdbc:mysql://localhost:3306/company?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: TDd1209!
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # 配置HTML访问目录
  mvc:
    view:
      prefix: /static/pages/
      suffix: .html


mybatis:
  mapper-locations: classpath:mapping/*.xml  #classpath就是应用程序resources的路径
  # 扫描实体类所在的位置
  type-aliases-package: com.demo.entity
  # 开启自动驼峰命名匹配
  configuration:
    map-underscore-to-camel-case: true



